# Generated by Django 3.0.7 on 2020-08-31 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0005_auto_20200901_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
