# Generated by Django 3.0.7 on 2020-09-01 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0006_auto_20200901_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Dis_Likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='unliked', to=settings.AUTH_USER_MODEL),
        ),
    ]
