# Generated by Django 3.0.7 on 2020-09-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_blogpost_dis_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='TotalView',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
