# Generated by Django 3.0.7 on 2020-09-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20200902_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforcode',
            name='user',
            field=models.CharField(max_length=500),
        ),
    ]
