# Generated by Django 3.0.7 on 2020-09-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_auto_20200904_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='TotalView',
            field=models.CharField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='requestforcode',
            name='Message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='requestforcode',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
