# Generated by Django 3.0.7 on 2020-09-04 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0015_auto_20200905_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Dis_Likes',
            field=models.ManyToManyField(blank=True, default=[0], related_name='unliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Likes',
            field=models.ManyToManyField(blank=True, default=[0], related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='TotalView',
            field=models.IntegerField(default=0),
        ),
    ]
