# Generated by Django 3.0.7 on 2020-09-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_problemstatement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemstatement',
            old_name='author',
            new_name='coder',
        ),
    ]
