# Generated by Django 3.0.7 on 2020-09-05 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_auto_20200905_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Related_To_Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField(verbose_name='')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProblemComment', to='Blog.ProblemStatement')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
