# Generated by Django 3.0.7 on 2020-09-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0019_comment_related_to_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyer_name', models.CharField(max_length=256)),
                ('reply', models.TextField(verbose_name='')),
                ('reply_created', models.DateTimeField(auto_now=True)),
                ('reply_updated', models.DateTimeField(auto_now=True)),
                ('reply_active', models.BooleanField(default=True)),
                ('replyto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reply', to='Blog.Comment_Related_To_Problem')),
            ],
            options={
                'ordering': ('-reply_created',),
            },
        ),
    ]
