# Generated by Django 3.0.7 on 2020-09-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_auto_20200906_0038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
