# Generated by Django 3.0.7 on 2020-09-05 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_related_to_problem',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Blog.Comment_Related_To_Problem'),
        ),
    ]
