# Generated by Django 3.0.7 on 2020-09-07 18:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0023_comment_related_to_problem_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffCampusRecruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('adminName', models.CharField(default='Yuvraj', max_length=20)),
                ('job_created', models.DateTimeField(auto_now=True)),
                ('job_updated', models.DateTimeField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('open', models.BooleanField(default=True)),
            ],
        ),
    ]
