# Generated by Django 3.0.7 on 2020-09-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0024_offcampusrecruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='offcampusrecruitment',
            name='totalView',
            field=models.IntegerField(default=0),
        ),
    ]
